services:
  redpanda:
    image: redpandadata/redpanda:v23.3.15
    container_name: redpanda
    # <<< CHANGE 1: THIS ENTIRE COMMAND BLOCK IS UPDATED
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:9093,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:9093,external://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  redpanda_console:
    image: redpandadata/console
    container_name: redpanda_console
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      # <<< CHANGE 2: THIS LINE IS UPDATED TO USE THE INTERNAL PORT
      KAFKA_BROKERS: "redpanda:9093"

networks:
  default:
    name: redpanda_network